version: '3'

services:
  crater_app:
    container_name: crater_app
    build:
      args:
        user: crater-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: crater-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated
    restart: always
    networks:
      - crater

  crater_db:
    container_name: crater_db
    image: mariadb
    restart: always
    volumes:
      - ./docker-compose/db/data:/var/lib/mysql:rw,delegated
    environment:
      MYSQL_USER: crater
      MYSQL_PASSWORD: crater
      MYSQL_ROOT_PASSWORD: crater
      MYSQL_DATABASE: crater
    restart: always
    networks:
      - crater 

  crater_nginx:
    container_name: crater_nginx
    image: nginx:1.17-alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    ports:
      - '8188:80'
    restart: always
    networks:
      - admin_default
      - crater

  crater_cron:
    container_name: crater_cron
    build:
      context: ./
      dockerfile: ./docker-compose/cron.dockerfile
    volumes:
      - ./:/var/www
    restart: always
    networks:
      - crater

volumes:
  db:

networks:
  crater:
    driver: bridge
  admin_default:
    external: true
